version: '3'
services:
  minio:
    image: quay.io/minio/minio
    hostname: minio-1
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_ACCESS_KEY= admin
      - MINIO_SECRET_KEY= admin1admin1admin1
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  minio-data:
