version: "2"
services:
  moodle:
    image: docker.io/bitnami/moodle:4.0.4-debian-11-r16
    environment:
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_DATABASE_TYPE=${MOODLE_DATABASE_TYPE}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      - MOODLE_SKIP_BOOTSTRAP=${MOODLE_SKIP_BOOTSTRAP}
      - MOODLE_SKIP_BOOTSTRAP=${MOODLE_SKIP_BOOTSTRAP}
      - MOODLE_SMTP_HOST=${MOODLE_SMTP_HOST}
      - MOODLE_SMTP_PORT=${MOODLE_SMTP_PORT}
      - MOODLE_SMTP_USER=${MOODLE_SMTP_USER}
      - MOODLE_SMTP_PASSWORD=${MOODLE_SMTP_PASSWORD}
      - MOODLE_SMTP_PROTOCOL=${MOODLE_SMTP_PROTOCOL}
    volumes:
      - "moodle_data:/bitnami/moodle"
      - "moodledata_data:/bitnami/moodledata"
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
