---
- name: Define hosts and vars
  hosts: all
  become: yes
  vars:

    users:
      - maya
      - mitra
      - houtan
      - heliya
  tasks:
    - name: Ensure sudo is installed
      package:
        name: sudo
        state: present

    - name: Create users with initial password
      user:
        name: "{{ item }}"
        password: "{{ '1' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
      with_items: "{{ users }}"

    - name: Set users password change on first login
      command: chage -d 0 "{{ item }}"
      with_items: "{{ users }}"

    - name: Add users to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
      with_items: "{{ users }}"

    - name: Find all users' home directories excluding root
      find:
        paths: /home
        file_type: directory
        recurse: no
      register: home_dirs

    - name: Remove authorized_keys for all users except root
      file:
        path: "{{ item.path }}/.ssh/"
        state: absent
      with_items: "{{ home_dirs.files }}"

    - name: Ensure pam_tty_audit is enabled for all users in sshd
      lineinfile:
        path: /etc/pam.d/sshd
        state: present
        insertafter: EOF
        line: 'session required pam_tty_audit.so enable=*'

    - name: Ensure pam_tty_audit is enabled in common-session (Debian/Ubuntu)
      lineinfile:
        path: /etc/pam.d/common-session
        state: present
        insertafter: EOF
        line: 'session required pam_tty_audit.so enable=*'
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Ensure pam_tty_audit is enabled in system-auth-ac (RHEL/CentOS)
      lineinfile:
        path: /etc/pam.d/system-auth-ac
        state: present
        insertafter: EOF
        line: 'session required pam_tty_audit.so enable=*'
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']
